### ISSUE TITLE
How can I run the v1.1 of ramdaq?

### ISSUE THREAD

**Issue by EikoSAIJOU334** [rikenbit/ramdaq#39]
Hi,
I've been using your great ramdaq pipeline via Nextflow.
A few days ago, I found a new version of ramdaq, but I failed to run the latest version.

I've already tested the command to update
"nextflow pull -all"
but when I run the rikenbit/ramdaq, the v1.0 worked.

I also tried the command 
"nextflow run rikenbit/ramdaq -r v1.1 -profile docker --reads '*{1,2}.fastq.gz' --genome GRCm38_vM25"

But the error message was returned as below.

Cannot find revision `v1.1` -- Make sure that it exists in the remote repository `https://github.com/rikenbit/ramdaq`

How can I use the latest version of ramdaq?
Thanks,

**Comment by myoshimura080822** [comment]
Hi @EikoSAIJOU334 !

Try this command.
(Please exclude "v" from the version specification.)
```
nextflow run rikenbit/ramdaq -r 1.1 -profile docker --reads '*{1,2}.fastq.gz' --genome GRCm38_vM25
```

Sorry for the confusion. We will add the instructions on how to specify the version in the manual.

**Comment by EikoSAIJOU334** [comment]
Thank you, Mr. Yoshimura!
I will try the command you mentioned.

Eiko
