### ISSUE TITLE
How can I improve the quantification by RSEM in ramdaq?

### ISSUE THREAD

**Issue by paniponi-becky** [rikenbit/RamDAQ#88]
Hello,

I used ramdaq to quantify the expression of our ramda-seq data.
It finishied without any errors, but the percentage of reads counted by RSEM was very low (about 30 to 40%). I checked MultiQC report and it told me that most of the reads had been classified as Unalignable reads.

I also tried running ramdaq with this data set (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE108463) and got the similar results.

Are there any options to be set to solve this problem?

These are  my environment and the options I set.

nextflow run rikenbit/ramdaq -profile singularity --genome GRCm38_vM25 --outdir result --reads 'SRR6413172_{1,2}.fastq.gz'

ramdaq v1.9.1
Nextflow v22.10.1
FastQC v0.11.8
Fastq-mcf v1.04.807
Hisat2 v2.2.0
Samtools v1.10
Bam2Wig v3.0.1
Bamtools v2.5.1
read_distribution v3.0.1
infer_experiment v3.0.1
inner_distance v3.0.1
junction_annotation v3.0.1
FeatureCounts v2.0.1
RSEM v1.3.1
R v3.6.3
edgeR v3.26.5
MultiQC v1.9

Thanks,

**Comment by myoshimura080822** [comment]
Hi @paniponi-becky,

SRR6413172 is not using NSR(Not so random primer) then it has high-level rRNA reads, so we do not recommend this sample as a positive control of ramdaq.

When we used RamDA-seq test data, they mapped about 60% uniquely or multiple at RSEM.(ex.GSE98664, single-end mESC). It can be low for some celltype, but some parameters need to be confirmed.
![image](https://user-images.githubusercontent.com/8693179/205201983-073cfd23-72fa-42e5-9961-a36075cc46e8.png)

Could you please check if the min/max read length setting of Fastqmcf (default: maxReadLength = 75, minReadLength = 36) is appropriate?

**Comment by paniponi-becky** [comment]
Hello,

Thank you for the information.

I haven't checked the settings of fastq-mcf. I'll check them at first.

**Comment by yuifu** [comment]
@paniponi-becky Hi, I'm one of the ramdaq developer team and have a simple question to help you solve the issue.

> I used ramdaq to quantify the expression of our ramda-seq data.

How your library DNA samples were sequenced? Specifically, 
(1) single-end or paired-end
(2) Read length (bp)

**Comment by paniponi-becky** [comment]
Hello,

Our data are paired-end data and the Read length is 150bp.
Is it too long?

**Comment by myoshimura080822** [comment]
@paniponi-becky 
Thanks for the infomation. The default readlength(maxReadLength 75) of Fastqmcf may be too short for that condition. Please retry ramdaq again with the following command.

nextflow run rikenbit/ramdaq -profile singularity --genome GRCm38_vM25 --minReadLength 32 --maxReadLength 150 --outdir result --reads 'XXXX_{1,2}.fastq.gz'

**Comment by paniponi-becky** [comment]
Thank you. I will try the command immediately after NIG supercomputer system becomes available again.

**Comment by paniponi-becky** [comment]
Hello,

I want to ask another question.
Should I remove PCR duplicates before inputting the data to ramdaq?
Or does ramdaq remove them automatically?

**Comment by myoshimura080822** [comment]
@paniponi-becky 
You don't have to remove PCR duplicates before using ramdaq. 

If the results of the ramdaq rerun are not improved, we want a few things to confirm. 
Then, please let us know the following.

- Library DNA mean length
- "Inner Distance” plot in MultiQC RSeQC section
- "Adapter Content” plot in MultiQC FastQC(trim, read1 and read2) section

**Comment by paniponi-becky** [comment]
I tried the command you showed, but it ended with this error.
I tried several times, but I couldn' t solve it.

Do you know what caused it?
I'm sorry for bothering you...

<img width="593" alt="02" src="https://user-images.githubusercontent.com/84619956/206836050-c1c0719d-916a-4f97-98b6-4f15810df67f.png">
<img width="575" alt="01" src="https://user-images.githubusercontent.com/84619956/206836053-86416f1d-e0e5-4d3e-8e50-2710a4d45b8c.png">

**Comment by myoshimura080822** [comment]
We would like to investigate this unknown error in detail.
So, would it be possible for you to share the following files? (in Dropbox, others)

- Fastq files as input for ramdaq
- MultiQC report (default options)

We would also like to contact you at the following address for file sharing. We look forward to hearing from you.

**Comment by paniponi-becky** [comment]
My supervisor allowed me to share the data.
I will send you the data tomorrow.

**Comment by yuifu** [comment]
@paniponi-becky Hi! Have you sent an email to support-bit @ riken.jp? We have not received it yet. If you already sent an email or there's anything we can do to help you send your report, please don't hesitate to let us know!

**Comment by paniponi-becky** [comment]
Hello,

I sent twice, but it seems that both of them didn't reach.
I guess that's because my e-mails contain multiqc report html file.

I will send you an e-mail again without the report.
Please wait a minute.

**Comment by paniponi-becky** [comment]
I sent you a new e-mail just now.
If it doesen't reach, please tell me here.

**Comment by myoshimura080822** [comment]
@paniponi-becky Thank you for your reply. We are very sorry, but it seems that we have not received any email from you at all.
Perhaps it is due to the security of our mail server.
Please wait a moment while we consider how to handle this issue.

**Comment by yuifu** [comment]
@paniponi-becky Is it possible for you to share multiqc report html file via a file sharing service (e.g., Dropbox, Google Drive, Next cloud, Box, ...). Then you can email just sharing a file link (not the file itself).

Also, we'd like to know the domain name of your email address (For example, if your email address is foobar@gmail.com we want to know `gmail.com`)

**Comment by paniponi-becky** [comment]
I uploaded all the files on GoogleDrive.

**Comment by myoshimura080822** [comment]
It has been confirmed that your mail has arrived in spam folder.
We will confirm the content immediately.

**Comment by myoshimura080822** [comment]
- An error occurred in the R script when using integer sample name
- Fixed in https://github.com/rikenbit/ramdaq/commit/5e044381b1997f62dc7024ea5bbbc5d042af417b
